"""Evidence-grounded product enrichment (Phase 6)."""

from .agent import EvidenceGroundedEnrichmentAgent
from .descriptions import (
    FORBIDDEN_SUPERLATIVES,
    DescriptionAgent,
    DescriptionCandidateEnvelope,
    DescriptionContext,
    DescriptionLimits,
    DescriptionService,
    DescriptionValidationResult,
    DescriptionValidator,
    DeterministicDescriptionBuilder,
    GuidelineAssessmentStatus,
)
from .models import (
    AttributePlan,
    AttributeSchema,
    EnrichmentCandidate,
    EnrichmentResult,
    EnrichmentStatus,
    FinalAttributeStatus,
    PublicationState,
    ReferenceAvailability,
    ReviewPayload,
    ValidationResult,
)
from .persistence import EnrichmentPersistence, PostgresEnrichmentRepository
from .planner import AttributePlanner
from .reference import (
    EXPECTED_REFERENCE_FILES,
    OFFICIAL_REFERENCE_MANIFEST,
    CategoryLovPack,
    FractionDecimalMap,
    GlobalLovIndex,
    LovAttributeRule,
    ManufacturerBrandIndex,
    ManufacturerBrandRecord,
    ReferencePack,
    ReferenceType,
    UomRecord,
    UomStandardMap,
    separate_value_and_uom,
)
from .service import EnrichmentService
from .validation import ValidationPipeline

__all__ = [
    "AttributePlan",
    "AttributePlanner",
    "AttributeSchema",
    "CategoryLovPack",
    "DescriptionAgent",
    "DescriptionCandidateEnvelope",
    "DescriptionContext",
    "DescriptionLimits",
    "DescriptionService",
    "DescriptionValidationResult",
    "DescriptionValidator",
    "DeterministicDescriptionBuilder",
    "EnrichmentCandidate",
    "EvidenceGroundedEnrichmentAgent",
    "EnrichmentResult",
    "EnrichmentPersistence",
    "EnrichmentService",
    "EnrichmentStatus",
    "EXPECTED_REFERENCE_FILES",
    "FinalAttributeStatus",
    "FORBIDDEN_SUPERLATIVES",
    "FractionDecimalMap",
    "GlobalLovIndex",
    "GuidelineAssessmentStatus",
    "LovAttributeRule",
    "ManufacturerBrandIndex",
    "ManufacturerBrandRecord",
    "OFFICIAL_REFERENCE_MANIFEST",
    "PostgresEnrichmentRepository",
    "PublicationState",
    "ReferenceAvailability",
    "ReferencePack",
    "ReferenceType",
    "ReviewPayload",
    "separate_value_and_uom",
    "UomRecord",
    "UomStandardMap",
    "ValidationPipeline",
    "ValidationResult",
]
