"""Phase 5 manufacturer-source retrieval and evidence primitives."""

from .agents import DiscoveryResult, ManufacturerDiscoveryAgent
from .core import (
    AsyncSourceFetcher,
    DocumentLink,
    DomainCircuitBreaker,
    DomainHealthStatus,
    DomainResolver,
    EvidenceCandidate,
    EvidenceExtractor,
    EvidenceSelector,
    HtmlParser,
    ManufacturerProfile,
    ParsedDocument,
    Phase5FailureReason,
    SafeNetworkTargetResolver,
    SourceCache,
    SourceFetcher,
    SourcePolicy,
    SourceRecord,
    SourceVerifier,
    canonicalize_url,
)
from .digital_assets import (
    DISALLOWED_THIRD_PARTY_DOMAINS,
    DOC_EXTENSIONS,
    IMAGE_EXCLUSION_KEYWORDS,
    KNOWN_MANUFACTURER_ASSET_HOSTS,
    AssetAssociationScope,
    AssetAuthorityVerifier,
    AssetBudgetConfig,
    AssetContentStatus,
    DigitalAssetDiscoveryService,
    DocumentClassifier,
)
from .html_extractor import (
    ExtractedField,
    ExtractedProductData,
    HtmlProductEvidenceExtractor,
)
from .mpn_normalizer import MpnHypothesis, MpnHypothesisType, MpnNormalizer
from .manufacturer_registry import ManufacturerRegistry
from .service import ManufacturerIntelligenceService
from .source_discovery import (
    DeterministicUrlStrategy,
    MpnMatchClassification,
    ProductIdentityMatch,
    ProductIdentityMatcher,
    ProductSourceCandidate,
    ProductSourceDiscoveryService,
)


__all__ = [
    "AssetAssociationScope",
    "AssetAuthorityVerifier",
    "AssetBudgetConfig",
    "AssetContentStatus",
    "AsyncSourceFetcher",
    "DISALLOWED_THIRD_PARTY_DOMAINS",
    "DOC_EXTENSIONS",
    "DeterministicUrlStrategy",
    "DigitalAssetDiscoveryService",
    "DiscoveryResult",
    "DocumentClassifier",
    "DocumentLink",
    "DomainCircuitBreaker",
    "DomainHealthStatus",
    "DomainResolver",
    "EvidenceCandidate",
    "EvidenceExtractor",
    "EvidenceSelector",
    "ExtractedField",
    "ExtractedProductData",
    "HtmlParser",
    "HtmlProductEvidenceExtractor",
    "IMAGE_EXCLUSION_KEYWORDS",
    "KNOWN_MANUFACTURER_ASSET_HOSTS",
    "ManufacturerDiscoveryAgent",
    "ManufacturerIntelligenceService",
    "ManufacturerProfile",
    "ManufacturerRegistry",
    "MpnHypothesis",

    "MpnHypothesisType",
    "MpnMatchClassification",
    "MpnNormalizer",
    "ParsedDocument",
    "Phase5FailureReason",
    "ProductIdentityMatch",
    "ProductIdentityMatcher",
    "ProductSourceCandidate",
    "ProductSourceDiscoveryService",
    "SafeNetworkTargetResolver",
    "SourceCache",
    "SourceFetcher",
    "SourcePolicy",
    "SourceRecord",
    "SourceVerifier",
    "canonicalize_url",
]
